<?php
echo $_POST['first_name'];
echo '<br />';
echo $_POST['middle_name'];
echo '<br />';
echo $_POST['last_name'];
echo '<br />';
echo $_POST['date'];
echo '<br />';
echo $_POST['email'];
echo '<br />';
echo $_POST['nationality'];
echo '<br />';
echo $_POST['citizenship'];
echo '<br />';
echo $_POST['address'];
echo '<br />';
echo $_POST['apt'];
echo '<br />';
echo $_POST['city'];
echo '<br />';
echo $_POST['country'];
echo '<br />';
echo $_POST['state'];
echo '<br />';
echo $_POST['zip_code'];
echo '<br />';
echo $_POST['mobile'];
echo '<br />';
echo $_POST['home_phone'];
echo '<br />';
echo $_POST['email'];
echo '<br />';
echo $_POST['fb'];
echo '<br />';
echo $_POST['Skype'];
echo '<br />';
echo $_POST['whatsapp'];
echo '<br />';
echo $_POST['twitter'];
echo '<br />';
echo $_POST['instagram'];
echo '<br />';
echo $_POST['google_plus'];
echo '<br />';
echo $_POST['work_name'];
echo '<br />';
echo $_POST['work_addr'];
echo '<br />';
echo $_POST['work_city'];
echo '<br />';
echo $_POST['work_county'];
echo '<br />';
echo $_POST['work_state'];
echo '<br />';
echo $_POST['work_zip_code'];
echo '<br />';
echo $_POST['work_email'];
echo '<br />';
echo $_POST['work_phone1'];
echo '<br />';
echo $_POST['ext1'];
echo '<br />';
echo $_POST['work_phone2'];
echo '<br />';
echo $_POST['ext1'];
echo '<br />';
echo $_POST['ext2'];